### ISSUE TITLE
Throwing errors on windows.

### ISSUE THREAD

**Issue by Boycce** [sindresorhus/sublime-autoprefixer#62]
Hey, autoprefixer has been working fine untill the last 2-3 weeks.
I am using sublime text 3.

```
Autoprefixer Error: 


C:\Users\Bettty\AppData\Roaming\Sublime Text 3\Packages\Autoprefixer\node_modules\postcss\lib\lazy-result.js:152

        this.processing = new Promise(function (resolve, reject) {
                              ^

ReferenceError: Promise is not defined

    at LazyResult.async (C:\Users\Bettty\AppData\Roaming\Sublime Text 3\Packages\Autoprefixer\node_modules\postcss\lib\lazy-result.js:152:31)

    at LazyResult.then (C:\Users\Bettty\AppData\Roaming\Sublime Text 3\Packages\Autoprefixer\node_modules\postcss\lib\lazy-result.js:75:21)

    at C:\Users\Bettty\AppData\Roaming\Sublime Text 3\Packages\Autoprefixer\autoprefixer.js:13:3

    at Socket.<anonymous> (C:\Users\Bettty\AppData\Roaming\Sublime Text 3\Packages\Autoprefixer\node_modules\get-stdin\index.js:23:3)

    at Socket.EventEmitter.emit (events.js:117:20)

    at _stream_readable.js:920:16

    at process._tickCallback (node.js:415:13)
```

**Comment by sindresorhus** [comment]
Upgrade Node.

**Comment by Boycce** [comment]
Cheers mate

**Comment by herrdu** [comment]
It works .Thank you!
