### ISSUE TITLE
Error when attempting to use

### ISSUE THREAD

**Issue by evu** [sindresorhus/sublime-autoprefixer#63]
Hi, awesome plugin, however it's recently stopped working...

Getting this error:

error: Autoprefixer
Error: 
/Users/admin/Library/Application Support/Sublime Text 3/Packages/Autoprefixer/node_modules/postcss/lib/lazy-result.js:152
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/Users/admin/Library/Application Support/Sublime Text 3/Packages/Autoprefixer/node_modules/postcss/lib/lazy-result.js:152:31)
    at LazyResult.then (/Users/admin/Library/Application Support/Sublime Text 3/Packages/Autoprefixer/node_modules/postcss/lib/lazy-result.js:75:21)
    at /Users/admin/Library/Application Support/Sublime Text 3/Packages/Autoprefixer/autoprefixer.js:13:3
    at Socket.<anonymous> (/Users/admin/Library/Application Support/Sublime Text 3/Packages/Autoprefixer/node_modules/get-stdin/index.js:23:3)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

Pops up and it's in console.

Sublime Text 3, Mac OS Yosemite.

**Comment by evu** [comment]
Turns out I just needed to update Node...
