### ISSUE TITLE
Autoprefixer command giving unexpected token error in sublime text 3

### ISSUE THREAD

**Issue by shmdhussain** [sindresorhus/sublime-autoprefixer#76]
when try to run the autoprefixer from my sublime text 3 , getting the following error. 

error: Autoprefixer
Error: /Users/Mohamed_Hussain_SH/Library/Application Support/Sublime Text 3/Packages/Autoprefixer/node_modules/get-stdin/index.js:2
const {stdin} = process;
      ^

```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Mohamed_Hussain_SH/Library/Application Support/Sublime Text 3/Packages/Autoprefixer/autoprefixer.js:2:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)


![Screenshot 2020-02-26 at 17 01 36](https://user-images.githubusercontent.com/4039657/75347401-181df800-58ba-11ea-8c4b-bb4ee65f990e.png)

```

screenshot attached. thanks in advance for any help
![Screenshot 2020-02-26 at 17 02 35](https://user-images.githubusercontent.com/4039657/75347346-fae92980-58b9-11ea-98c6-07fc14fa8d61.png)

**Comment by sindresorhus** [comment]
You have a very old Node.js version. Upgrade that.

**Comment by shmdhussain** [comment]
Thanks @sindresorhus  I am also suspecting that one since I start using nvm long time back. Is there a way to update the nodejs version that sublime to use

**Comment by shmdhussain** [comment]
It works!!!  after I made the symliunk for the latest node bin which is in the path(usually in this path for mac os) to /usr/local/bin/ folder like below

`ln -s /Users/Mohamed_Hussain_SH/.nvm/versions/node/v10.11.0/bin/node /usr/local/bin/node`

trick is your node binary or its symlink should be in the /usr/local/bin/folder , It didnt work even it is in $PATH
