### ISSUE TITLE
Sublime text 3 autoprefixer stopped working

### ISSUE THREAD

**Issue by Giovancruz** [sindresorhus/sublime-autoprefixer#84]
Hi,

Before I was able to use the package normally, but for some time it stopped working, here is the error shown to me:
```
    Autoprefixer
        Error: /home/gcruz/.config/sublime-text-3/packages/Autoprefixer/
        node_modules/get-stdin/index.js:13
              for await (const chunk of stdin) {
                   ^^^^^
        SyntaxError: Unexpected reserved word
          at new Script (vm.js:51:7)
          at createscript (vm.js:136: 10)
          at Object. runlnThisContext (vm.js:197:10)
          at Module._compile (module.js:613:28)
          at Object.Module._extensions..js (module.js:660:10)
          at Module.load (module.js:561:32)
          at tryModuleLoad (module.js:501:12)
          at Function.Module._load (module.js:493:3)
          at Module.require (module.js:593:17)
          at require (internal/module.js:11:18)
```

`npm -v` on cmd results: `v10.15.3`

I've tried to reinstall the package but it does'nt work.

**Comment by sindresorhus** [comment]
You need to upgrade your Node.js version.
